Use printf instead of echo for colored output

diff --git a/.git_template/hooks/pre-push b/.git_template/hooks/pre-push
--- a/.git_template/hooks/pre-push
+++ b/.git_template/hooks/pre-push
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 if [ "$(git rev-parse --abbrev-ref HEAD | grep '^wip')" ]; then
-    echo "\033[0;31m[ABORT] You cannot push a branch whose prefix is \`wip\`.\033[0;39m" 1>&2
+    printf "\033[0;31m[ABORT] You cannot push a branch whose prefix is \`wip\`.\033[0;39m\n" 1>&2
     exit 1
 fi
 
@@ -9,7 +9,7 @@ default_branch=$(git rev-parse --abbrev-ref origin/HEAD 2>/dev/null | sed 's@^or
 default_branch=${default_branch:-main}
 
 if [ "$(git log --oneline "${default_branch}..HEAD" | grep 'fixup! ')" ]; then
-    echo "\033[0;31m[ABORT] You cannot push a commit whose title starts \`fixup! \`.\033[0;39m" 1>&2
+    printf "\033[0;31m[ABORT] You cannot push a commit whose title starts \`fixup! \`.\033[0;39m\n" 1>&2
     exit 1
 fi
 
